apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wp2
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/aamir454/helm3.git
    targetRevision: HEAD
    path: wp2
  destination: 
    server: https://kubernetes.default.svc
    namespace: nswordpress

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true