{{- if or .Values.mariadb.enabled .Values.externalDatabase.host -}}
apiVersion: {{ template "phpbb.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: "{{ template "phpbb.fullname" . }}"
  labels:
    app: "{{ template "phpbb.fullname" . }}"
    chart: "{{ template "phpbb.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  selector:
    matchLabels:
      app: "{{ template "phpbb.fullname" . }}"
      release: {{ .Release.Name | quote }}
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ template "phpbb.fullname" . }}"
        chart: "{{ template "phpbb.chart" . }}"
        release: {{ .Release.Name | quote }}
{{- if or .Values.podAnnotations .Values.metrics.enabled }}
      annotations:
  {{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
  {{- end }}
  {{- if .Values.metrics.podAnnotations }}
{{ toYaml .Values.metrics.podAnnotations | indent 8 }}
  {{- end }}
{{- end }}
    spec:
{{- include "phpbb.imagePullSecrets" . | indent 6 }}
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "status.localhost"
      containers:
      - name: "{{ template "phpbb.fullname" . }}"
        image: {{ template "phpbb.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: {{ .Values.allowEmptyPassword | quote }}
        - name: MARIADB_HOST
          value: mariadb.nsmysql
        - name: MARIADB_PORT_NUMBER
          value: "3306"
        - name: PHPBB_DATABASE_NAME
          value: phpbb-db
        - name: PHPBB_DATABASE_USER
          value: root
        - name: PHPBB_DATABASE_PASSWORD
          value: Aamir@1122
        - name: PHPBB_USERNAME
          value: admin
        - name: PHPBB_PASSWORD
          value: Aamir@1122
        - name: PHPBB_EMAIL
          value: aamir454@gmail.com
        - name: SMTP_HOST
          value: {{ .Values.smtpHost | quote }}
        {{- end }}
        {{- if .Values.smtpPort }}
        - name: SMTP_PORT
          value: {{ .Values.smtpPort | quote }}
        {{- end }}
        {{- if .Values.smtpUser }}
        - name: SMTP_USER
          value: {{ .Values.smtpUser | quote }}
        {{- end }}
        {{- if .Values.smtpPassword }}
        - name: SMTP_PASSWORD
          value: password
        - name: SMTP_PROTOCOL
          value: {{ default "" .Values.smtpProtocol | quote }}
        {{- end }}
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        livenessProbe:
          httpGet:
            path: /ucp.php
            port: http
          initialDelaySeconds: 120
        readinessProbe:
          httpGet:
            path: /ucp.php
            port: http
          initialDelaySeconds: 30
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: phpbb-data
          mountPath: /bitnami/phpbb
{{- if .Values.metrics.enabled }}
      - name: metrics
        image: {{ template "phpbb.metrics.image" . }}
        imagePullPolicy: {{ .Values.metrics.image.pullPolicy | quote }}
        command: [ '/bin/apache_exporter', '-scrape_uri', 'http://status.localhost:80/server-status/?auto']
        ports:
        - name: metrics
          containerPort: 9117
        livenessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
  {{ toYaml .Values.metrics.resources | indent 10 }}
{{- end }}
      volumes:
      - name: phpbb-data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: "{{ template "phpbb.fullname" . }}-phpbb"
      {{- else }}
        emptyDir: {}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
{{- end }}
