{{- if .Values.istio.virtualservice.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
spec:
  hosts:
  - {{ template "hostUrl" . }}
    {{ if .Values.istio.virtualservice.extra_host }}
  - {{ .Values.istio.virtualservice.extra_host }}
    {{ end }}
  gateways: 
  - {{ .Values.global.gateway }}
  http:
{{ toYaml .Values.istio.virtualservice.http | indent 2 }}
{{- end -}}